### PR TITLE
Test Failure

### LINKED ISSUE #47: Test that properties fail correctly
The test for `exists` in #45 is simply returning `true`. A more interesting property of `exists` is its failure when something _doesn’t_ exist.

My tests in [Assertions](https://github.com/antitypical/Assertions) do [a little trickery](https://github.com/antitypical/Assertions/blob/master/AssertionsTests/AssertionsTests.swift#L81-L113) ([discovered by](https://github.com/antitypical/Assertions/pull/3#issuecomment-76337761) @ishkawa) to enable testing assertion failures without actually failing its own tests. It would be nice to use something like this to test that properties which don’t hold, fail.

### PR DESCRIPTION
**Pull request by CodaFi**
Fixes #47 

@robrix You got a favorite tautology you want me to negate in here?

### CODE REVIEW

**Comment by CodaFi** [comment]
:boat:

File: SwiftCheckTests/FailureSpec.swift [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+		forAll { (_ : Int) in false },
+		forAll { (x : Int) in x != x },
+		forAll { (b : Bool) in !(b || !b) },
+		forAll { (x : Int) in x > (x + 1) },
+		forAll { (x : Int, y : Int, c : Int) in (x > y) ==> x + c < y + c },
+		forAll { (x : Int, y : Int, c : Int) in (x > y) ==> x - c < y - c },
+		forAll { (x : Int, y : Int, c : Int) in (x > y) ==> x * c < y * c },
+		forAll { (x : Int, y : Int, c : Int) in (x > y && c != 0) ==> x / c < y / c },
+		forAll { (x : Int, y : Int, c : Int) in (x > y && c != 0) ==> x / (-c) > y / (-c) },
+	]
```
Comment (robrix) [inline SwiftCheckTests/FailureSpec.swift]: These are great :+1:

**Comment by robrix** [comment]
Thanks @CodaFi! :heart:
